### ISSUE TITLE
Could you provide a demo?

### ISSUE THREAD

**Issue by sergical** [miguelalarcos/flow-router-pagination#1]
Having trouble setting it up in my case judging from the explanation. No idea where `Counts` is coming from. So it would be nice to see a demo/full code to get this thing working.

**Comment by miguelalarcos** [comment]
ok, you are right, the explanation is short. I will write a demo soon.

(Count comes from package `tmeasday:publish-counts`)

**Comment by miguelalarcos** [comment]
Now there is an example in the package. Please let me know if this helps.

Note that still the limit of documents to retrieve is hardcoded in several places. I have to find the way to set this in one place.

**Comment by miguelalarcos** [comment]
http://localhost:3000/?page=0

**Comment by sergical** [comment]
@miguelalarcos thanks for the demo, it's a lot more clear now, however `queryParams.page` returns `NaN`. any idea why that's happening? here's my `router.js`

```
FlowRouter.route('/discovery', {
  name: 'discover',
  subscriptions: function(params, queryParams) {
    var limit, offset, page;
    page = parseInt(queryParams.page) || 0;
    console.log(queryParams)
    console.log(page);
    limit = 10;
    offset = page * limit;
    return this.register('careerPaths', Meteor.subscribe('careerPaths', offset, limit));
  },
  action: function(params, queryParams) {
    return FlowLayout.render('layout', {
      top: 'header',
      main: 'discovery'
    });
  }
});
```

**Comment by miguelalarcos** [comment]
Does it return _NaN_ even if you go to `/discovery/?page=0` ?

**Comment by sergical** [comment]
nope, it returns 0. When i first route to `/discovery` the template at the bottom only has `-` and `+` and when i hit plus it goes to `/discovery?page=NaN`

**Comment by miguelalarcos** [comment]
Are you using v0.1.2?

**Comment by sergical** [comment]
ok so updating to `0.1.2` fixed the issue however it's still rendering the same documents regardless of which page i am on

**Comment by miguelalarcos** [comment]
Could I see your project on github? I don't know the reason of that issue, sorry.

**Comment by sergical** [comment]
it's actually a private repo on bitbucket. any code snippets i can provide that would be helpful?

**Comment by miguelalarcos** [comment]
I would start taking a look at the discovery helpers and the publication 'careerPaths'

**Comment by sergical** [comment]
i forgot i still had `autopublish`. it works great now. just the matter of removing the plus/minus when there isn't a different page to load so it doesn't display nothing and making the number of pages be dynamic. thanks for your help though

**Comment by miguelalarcos** [comment]
Good point. Please tell me any thing you need.

**Comment by sergical** [comment]
Also, I have Session variables that set up filters for my query

```
    var filter = Session.get('work_styles');
    var keys = Object.keys(filter);
    var query = {};
    keys.forEach(function(key){
        query["workStyle."+key] = filter[key];
    });
    return CareerPaths.find(query, {limit: 10, sort: {createdAt: 1}});
```

So when I start using the filter, each page fill get filtered, as opposed to bringing queries from the following pages to the top. for example after initiating a filter, the first page displays 2 documents, the second page will display 6. is there a workaround for that?

**Comment by miguelalarcos** [comment]
Can I see your publish? I think you need to pass the query to that publication. It means you should have those keys of the query in the url.

**Comment by miguelalarcos** [comment]
v0.1.3
now the minus and plus buttons are not shown if they are not needed.

**Comment by sergical** [comment]
```
Meteor.publish('careerPaths', function(skip, limit) {
  var options;
  Counts.publish(this, 'total_career_paths', CareerPaths.find());
  if (skip < 0) {
    skip = 0;
  }
  options = {};
  options.skip = skip;
  options.limit = limit;
  if (options.limit > 10) {
    options.limit = 10;
  }
  options.sort = {
    createdAt: 1
  };
  return CareerPaths.find({}, options);
});
```

since publish is done on server, i don't know how to get the session filters in there

**Comment by 416serg** [comment]
also, i think the new update messed up the subscriptions, i am getting the same documents on each page again

**Comment by miguelalarcos** [comment]
I think that the key value of the filter should go this way:
`Meteor.publish('careerPaths', function(skip, limit, filter)`
But I am not sure.

Do we have a regression? I don't know why because I just have hidden the buttons where they are not needed. I am going to check this.

**Comment by sergical** [comment]
@miguelalarcos disregard the comment i deleted, it all works fine :)

**Comment by miguelalarcos** [comment]
happy :)

**Comment by sergical** [comment]
`Meteor.publish('careerPaths', function(skip, limit, filter)` so then in the router i'd subscribe with `return this.register('careerPaths', Meteor.subscribe('careerPaths', offset, limit, filter));` where filter is my session filter?

**Comment by miguelalarcos** [comment]
I think you should try this approximation...

**Comment by sergical** [comment]
i can't use session variables inside router subscriptions

**Comment by miguelalarcos** [comment]
maybe you could have a `Tracker.autorun` that sets the key, value in the url whenever a Session change.
For example, you have in your filter the key 'name'. Then, when it changes you should `FlowRouter.setQueryParams({name: value})`
Then inside router subscription you can get the value from the url with `FlowRouter.getQueryParam('name')`

I don't know how complicated should be the `Tracker.autorun` and I don't know if it's the best solution.

**Comment by sergical** [comment]
`FlowRouter.setQueryParams({name: value})` set query params adds a new query param each time. i'd want it to update if the same filter changes. is there a simple way to do an update on the queryParams?

**Comment by miguelalarcos** [comment]
This is my code. The query param `page` is updated and not added.

``` coffee
Template.paginationBar.events
  'click .plus': (e, t) ->
    current = parseInt(FlowRouter.getQueryParam('page')) or 0
    FlowRouter.setQueryParams({page: current + 1})
```

I'm not sure what happens to you.

**Comment by 416serg** [comment]
do you know if there is a quick way to get the some of the query params? i need all the ones after `pages`. so i have `?page=1&schedule=-1&location=0` and i need to get an object with only `schedule=-1&location=0`?
