### ISSUE TITLE
Automatic page counter?

### ISSUE THREAD

**Issue by sergical** [miguelalarcos/flow-router-pagination#2]
Is that something we can expect within the next few updates?

**Comment by miguelalarcos** [comment]
I'm not sure to understand. What exactly do you mean?

**Comment by sergical** [comment]
inside `{{> paginationBar itemsPerPage=3 window=5 count='total_posts'}}` make `window` be automatic depending on the collection count / itemsPerPage

**Comment by miguelalarcos** [comment]
with a limit? Imagine a count of 100 and itemsPerPage of 5. The bar will be 20, what I understand is very big.

**Comment by sergical** [comment]
right, but then it doesn't even change to 6, 7, 8, 9, etc, when you get to let's say 5. What ususally happens is you have something like 1,2,3,4, ..., 20 and if you go to page 4 let's say it will be 1, ..., 4, 5, 6, 7, ..., 20. any thoughts around that?

**Comment by miguelalarcos** [comment]
hum, interesting. And what about two buttons, at the init and end of the bar: <<     >>   to go to the initial position or to the end?

**Comment by sergical** [comment]
well there could be on each side `<< -` and `+ >>` where a click on `-` or `+` will increment or decrease page by 1 and click on the double arrows that will go to the end or the beginning

**Comment by miguelalarcos** [comment]
ok, let me find the time and I will implement it as soon as possible. Thanks for your contribution.

**Comment by sergical** [comment]
awesome :)

**Comment by miguelalarcos** [comment]
could you try it, please? (version 0.1.5)

**Comment by sergical** [comment]
So then just remove the `<<` or `>>` when you're at the beginning or end of the list. my issue is that when i initially load up my documents, i have 5 pages, but then when i initiate a filter, the documents take up only the first 2 pages but i still have those numbers for 3, 4, 5 that display nothing.

**Comment by miguelalarcos** [comment]
ok.
I have no way of calculating the total when you use the filter (I use the Counts object). I can't imagine a solution. Are you sending the filter to the server or not?

**Comment by sergical** [comment]
yes, i am :) i think i'll be able to figure it out

**Comment by sergical** [comment]
figured it out :) so yeah, if you could remove `<<` when you're on page 1 and remove `>>` when you're on the last page and maybe not show `<< and >>` if the number of pages is less than what's specified in `window`

**Comment by miguelalarcos** [comment]
"""
 if you could remove << when you're on page 1 and remove >> when you're on the last page 
"""

I will implement that solution.

**Comment by sergical** [comment]
thanks :)

**Comment by miguelalarcos** [comment]
v0.1.6 uploaded
